AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  StartEC2Instances:
    Type: 'AWS::Serverless::Function'
    Properties:
      PackageType: Image
      ImageUri: '721790918739.dkr.ecr.ap-south-1.amazonaws.com/scheduler-lambda:latest'
      ImageConfig:
        Command: ["start.handler"]
      # Handler: start.handler
      # Runtime: python3.9
      # CodeUri: scheduler_crons/.
      Description: 'starts ec2 instances'
      # MemorySize: 128
      # Timeout: 3
      Role: 'arn:aws:iam::721790918739:role/SchedulerLambdaRole'
      Tracing: Active
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(30 3 ? * 2-6 *)
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1
   
  StopEC2Instances:
    Type: 'AWS::Serverless::Function'
    Properties:
      PackageType: Image
      ImageUri: '721790918739.dkr.ecr.ap-south-1.amazonaws.com/scheduler-lambda:latest'
      ImageConfig:
        Command: ["stop.handler"]
      # Handler: start.handler
      # Runtime: python3.9
      # CodeUri: scheduler_crons/.
      Description: 'stops ec2 instances'
      # MemorySize: 128
      # Timeout: 3
      Role: 'arn:aws:iam::721790918739:role/SchedulerLambdaRole'
      Tracing: Active
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 ? * 2-6 *)
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1
  # LibsLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: blank-python-lib
  #     Description: Dependencies for the blank-python sample app.
  #     ContentUri: package/.
  #     CompatibleRuntimes:
  #       - python3.9
